/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationsVerifyRouteImport } from './routes/conversations/verify'
import { Route as ConversationsMeRouteImport } from './routes/conversations/me'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin/messages'
import { Route as AuthenticatedAdminParticipantsIndexRouteImport } from './routes/_authenticated/admin/participants/index'
import { Route as AuthenticatedAdminMessagesIndexRouteImport } from './routes/_authenticated/admin/messages/index'
import { Route as AuthenticatedAdminMessagesMessageIdRouteImport } from './routes/_authenticated/admin/messages/$messageId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsVerifyRoute = ConversationsVerifyRouteImport.update({
  id: '/conversations/verify',
  path: '/conversations/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsMeRoute = ConversationsMeRouteImport.update({
  id: '/conversations/me',
  path: '/conversations/me',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminParticipantsIndexRoute =
  AuthenticatedAdminParticipantsIndexRouteImport.update({
    id: '/admin/participants/',
    path: '/admin/participants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMessagesIndexRoute =
  AuthenticatedAdminMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminMessagesRoute,
  } as any)
const AuthenticatedAdminMessagesMessageIdRoute =
  AuthenticatedAdminMessagesMessageIdRouteImport.update({
    id: '/$messageId',
    path: '/$messageId',
    getParentRoute: () => AuthenticatedAdminMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/conversations/me': typeof ConversationsMeRoute
  '/conversations/verify': typeof ConversationsVerifyRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
  '/admin/participants/': typeof AuthenticatedAdminParticipantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/conversations/me': typeof ConversationsMeRoute
  '/conversations/verify': typeof ConversationsVerifyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesIndexRoute
  '/admin/participants': typeof AuthenticatedAdminParticipantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/register': typeof RegisterRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/conversations/me': typeof ConversationsMeRoute
  '/conversations/verify': typeof ConversationsVerifyRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/messages/$messageId': typeof AuthenticatedAdminMessagesMessageIdRoute
  '/_authenticated/admin/messages/': typeof AuthenticatedAdminMessagesIndexRoute
  '/_authenticated/admin/participants/': typeof AuthenticatedAdminParticipantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/me'
    | '/register'
    | '/rules'
    | '/signup'
    | '/verify-email'
    | '/conversations/me'
    | '/conversations/verify'
    | '/admin/messages'
    | '/admin/'
    | '/admin/messages/$messageId'
    | '/admin/messages/'
    | '/admin/participants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/me'
    | '/register'
    | '/rules'
    | '/signup'
    | '/verify-email'
    | '/conversations/me'
    | '/conversations/verify'
    | '/admin'
    | '/admin/messages/$messageId'
    | '/admin/messages'
    | '/admin/participants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/login'
    | '/me'
    | '/register'
    | '/rules'
    | '/signup'
    | '/verify-email'
    | '/conversations/me'
    | '/conversations/verify'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/messages/$messageId'
    | '/_authenticated/admin/messages/'
    | '/_authenticated/admin/participants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  RegisterRoute: typeof RegisterRoute
  RulesRoute: typeof RulesRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ConversationsMeRoute: typeof ConversationsMeRoute
  ConversationsVerifyRoute: typeof ConversationsVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/verify': {
      id: '/conversations/verify'
      path: '/conversations/verify'
      fullPath: '/conversations/verify'
      preLoaderRoute: typeof ConversationsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/me': {
      id: '/conversations/me'
      path: '/conversations/me'
      fullPath: '/conversations/me'
      preLoaderRoute: typeof ConversationsMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/participants/': {
      id: '/_authenticated/admin/participants/'
      path: '/admin/participants'
      fullPath: '/admin/participants/'
      preLoaderRoute: typeof AuthenticatedAdminParticipantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/messages/': {
      id: '/_authenticated/admin/messages/'
      path: '/'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AuthenticatedAdminMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminMessagesRoute
    }
    '/_authenticated/admin/messages/$messageId': {
      id: '/_authenticated/admin/messages/$messageId'
      path: '/$messageId'
      fullPath: '/admin/messages/$messageId'
      preLoaderRoute: typeof AuthenticatedAdminMessagesMessageIdRouteImport
      parentRoute: typeof AuthenticatedAdminMessagesRoute
    }
  }
}

interface AuthenticatedAdminMessagesRouteChildren {
  AuthenticatedAdminMessagesMessageIdRoute: typeof AuthenticatedAdminMessagesMessageIdRoute
  AuthenticatedAdminMessagesIndexRoute: typeof AuthenticatedAdminMessagesIndexRoute
}

const AuthenticatedAdminMessagesRouteChildren: AuthenticatedAdminMessagesRouteChildren =
  {
    AuthenticatedAdminMessagesMessageIdRoute:
      AuthenticatedAdminMessagesMessageIdRoute,
    AuthenticatedAdminMessagesIndexRoute: AuthenticatedAdminMessagesIndexRoute,
  }

const AuthenticatedAdminMessagesRouteWithChildren =
  AuthenticatedAdminMessagesRoute._addFileChildren(
    AuthenticatedAdminMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminParticipantsIndexRoute: typeof AuthenticatedAdminParticipantsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminParticipantsIndexRoute:
    AuthenticatedAdminParticipantsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  RegisterRoute: RegisterRoute,
  RulesRoute: RulesRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ConversationsMeRoute: ConversationsMeRoute,
  ConversationsVerifyRoute: ConversationsVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
